### ISSUE TITLE
在iOS 11上无法显示

### ISSUE THREAD

**Issue by SunsgneDZ** [WJCha/MBProgressHUD-WJExtension#1]
在iOS 11上无法显示。（之前都可以正常显示），还有一个神奇的现象，比如说一个输入框处于编辑状态，点击检测按钮，提示框正常显示，如果输入框处于非编辑状态，点击检测按钮无法显示提示框.

**Comment by WJCha** [comment]
你好
- 关于在 iOS 11 上的使用问题，由于我暂时还没有升级xcode, 暂时还不清楚呢。等后面我升级xcode后再看看；
- 至于你提到的一个神奇现象，我不太清楚你所描述的要怎么去复现，接下来我会多尝试一下看看。如果你能提供更多的信息就更好了； 
- 在指定弹框所在的 view 的时候，在控制器上你可以尝试 传 self.view 代替 nil 试试。希望可以帮到你。

**Comment by AlwaysYang** [comment]
是获取window 出的问题。
可以使用[UIApplication sharedApplication].keyWindow
@SunsgneDZ
